### ISSUE TITLE
Difficulties in adoption of code 

### ISSUE THREAD

**Issue by Danfoa** [Denys88/rl_games#112]
Hi to all, 

First, congrats on the work. It is truly appealing.

I came to use RL-games repo through the IsaacGymEnvs repository. I am extending several of my works to operate on this new simulator with IsaacGymEnvs which have as dependency the 1.1.3 version of rl-games. 

This issue is more of a request/advise to have a more organized and structured repository and collaboration framework. Things that I believe could help encouraging contributions from third party and a larger adoption of your repository are:

- Release version tags
- Commits with version numbering 
- Enforcing abstract class inheritance on algorithms and builders. This will eliminate problems such as using different words for the same concepts (`frame`, `step`), (`epoch`, `episode`) which lead to confusions and probably bugs as these are in reality different concepts. 
- Not documented configurations. 
- Reduce number of branches with identifiable goals.

Perhaps it would be useful to clarify and standarize some concepts like:

- `step`: Step can reefer to simulation step, or to a single agent simulation/experience step. In this case of parallel simulation a single simulation step accounts for multiple experience "steps".
- `frame`: Its unclear how you use this concept, sometimes it seems to reefer to a simulation step, and sometimes to epochs. 
- `epoch`: User defined numerical value to trigger a logging sequence of metrics and statistics. **The units** with which you define this and other frequency variables (e.g., `max_iterations`) is also ambiguous as sometimes it appears to be defined in terms of samples of experience collected (preferably) and sometimes in epochs or batches (dependent on specific size of batch or epoch). 
- `actor`: in your implementation of SAC the concepts of  `actors`, `agents` and `envs` are constantly interchanged generating confusion. For the sake of generality (multi agent) an `env` might hold multiple `agents` and each agent could have multiple `actor` networks.  

I was cleaning and fixing some of the bugs of your SAC implementation when I found all of this problems, which have made it really difficult to contribute, and to work with different versions of the repo code with which IsaacGymEnvs depends on.

**Comment by ViktorM** [comment]
Hi @Danfoa,

Thanks for your detailed feedback. For quite a long time our the main focus was on the performance and beating state-of-the-art results in different areas - discrete and continuous control, games, multi-agent, and self-play environments.

Now we are going to focus more now on the usability side, and we started working on cleaning up the code and improving naming and documentation.

Can you also provide some more details about SAC bugs?

**Comment by Denys88** [comment]
Hi @Danfoa, 
Thank you for your feedback
We've already started addressing your comments.
Readme update is here: https://github.com/Denys88/rl_games/pull/114
