### ISSUE TITLE
Ray or hvd

### ISSUE THREAD

**Issue by 1seck** [Denys88/rl_games#116]
Hi there 
Why is horovod needed if you have ray? Ray can also run on multiple GPUs. And do both not interfere? And where are the parameters handled? In rays database or hvd?
Kind regards

**Comment by Denys88** [comment]
Hi, I see you already closed it. But Ill answer anyway.
Ray is used for cpu environments only. Also I didn't find the way how to use it in efficient way for multigpu use-case with NCCL for example.
Imaging you are going to use my library to train atari and you have multi gpu setup. You will use libraries for this case. 
For the IsaacGym case they provide their own vectorized env on gpu so horovod is the fastests.

**Comment by 1seck** [comment]
Hi, thank you for answering. Ok, and horovod can also be used if spread
over multiple machines? Maybe that's not necessary for the GPU case.

Kind regards

Denys Makoviichuk ***@***.***> schrieb am Di., 18. Jan. 2022,
00:03:
