### ISSUE TITLE
Using SAC 

### ISSUE THREAD

**Issue by BY571** [Denys88/rl_games#124]
Hi, 

I saw you were working on making it possible to train SAC agents with rl_games. Is that possible already? I was checking the configs and couldn't find anything. Everything seems ppo related. So I guess you can't run SAC currently?

**Comment by Denys88** [comment]
Hi [BY571](https://github.com/BY571), SAC works. @ViktorM  should have some yaml configs for IsaacGym.

**Comment by boxiXia** [comment]
also this line need a quick fix from
 https://github.com/Denys88/rl_games/blob/25e654c3a432ac7da6bc6071bcf58aeb88f4aa9e/rl_games/algos_torch/players.py#L187

to 
```python
obs_shape = torch_ext.shape_whc_to_cwh(self.obs_shape)
```

**Comment by ViktorM** [comment]
Thanks for finding a fix, @boxiXia! It worked in my tests. Will push the fixes soon.

About the config proposed fix, only fixed_sigma was missing and required:

```
    space:
      continuous:
        fixed_sigma: True
```
