### ISSUE TITLE
Sequential Multi-agent PPO with DR

### ISSUE THREAD

**Issue by ishitamed19** [Denys88/rl_games#136]
Hi,
I have a few doubts wrt to implementing multiple agents in Isaac Gym (or Brax). (apologies if they are too trivial)

I want to use 2 or more agents in the same experiment (agents will have different environments, especially if Domain Randomisation is enabled) and train them sequentially (i.e. first Agent 1 gets trained via PPO, then Agent 2 and so on...)

How can I go about implementing this? I am not sure which files I should be modifying and how to configure `train.py` to support the above functionality.

Thanks!

**Comment by ViktorM** [comment]
Hi @ishitamed19,

I don't know your use case and the type of environment you are working with, but as a good example of implementing a curriculum can be anymal terrain env in Isaac Gym Envs: https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/main/isaacgymenvs/tasks/anymal_terrain.py
