### ISSUE TITLE
Customize the terminal output to show epoch progress?

### ISSUE THREAD

**Issue by erwincoumans** [Denys88/rl_games#143]
This is a great project, thanks!

The current output of rl_games to the terminal doesn't show progress. 

I know you can use Tensorboard etc, but is there a way to customize the terminal output, to include information, such as Episode [4/500], similar but less verbose than [rsl_rl](https://github.com/leggedrobotics/rsl_rl) / [legged_gym](https://github.com/leggedrobotics/legged_gym)?

**Comment by erwincoumans** [comment]
Thanks, that helps.
self.max_epochs is not plumbed through the APIs, so I suppose I still have to modify a2c_common.py to add a print?

**Comment by Denys88** [comment]
@erwincoumans  you can add print directly. Or if you decide to use observer you can get access to everything using self.algo in the Observer class. I am thinking that the most fancy solution is to move my print to the Observer.

**Comment by erwincoumans** [comment]
Please consider a small change, I'm sure others will find it helpful as well (since it is good to know how far the progress is)
https://github.com/Denys88/rl_games/pull/144

**Comment by Denys88** [comment]
merged.
