### ISSUE TITLE
How to get rl_games==1.1.4 source code

### ISSUE THREAD

**Issue by nuomizai** [Denys88/rl_games#154]
How can I get the rl_games v1.1.4 source code which is required by the IsaacGymEnvs. I want to add my own algorithms in rl_games. Therefore, I need to get the source code. Does anyone know how to do that?

**Comment by Denys88** [comment]
hey, @nuomizai  I just updated IsaacGym fork to make it work with the lastest rl_games.
I suggest you to use just latest master or 1.4.0 version.
Unfortunately I just started to create version tags.
Thanks,
Denys

**Comment by nuomizai** [comment]
> hey, @nuomizai I just updated IsaacGym fork to make it work with the lastest rl_games. I suggest you to use just latest master or 1.4.0 version. Unfortunately I just started to create version tags. Thanks, Denys

Thank for your help, @Denys88 .
