### ISSUE TITLE
Debugging multi-GPU issue

### ISSUE THREAD

**Issue by vwxyzjn** [Denys88/rl_games#161]
In IsaacGymEnvs, rl-games + multiGPU seems to have some issues. As shown in the screenshot, rl-games + multiGPU performs uses twice amount of data and performs worse than the single GPU setting in `Ant`

![image](https://user-images.githubusercontent.com/5555347/169843187-09563b21-5b8b-4448-9769-f24e17b3ff19.png)

This issue tracks the investigation of this issue.

## Proposed debugging route

I suggest making sure we make sure there is no loss in sample efficiency first before scaling to more envs by matching implementation details in our prototype in CleanRL: https://cleanrl-git-new-multi-gpu-vwxyzjn.vercel.app/rl-algorithms/ppo/#implementation-details_6. 

### 1. Seeding logic and configuration issue

- [x] https://github.com/Denys88/rl_games/pull/162

We need to seed multiGPU processes with different seeds to decorrelate experience, otherwise the multiGPU processes will produce the exact observations. 

Configuration-wise we can set the overall seed with `params.seed` and env seed with `params.config.env_config.seed`, so if `params.config.env_config.seed` is set but  `params.seed` is not set, we get identical observations from the environments as shown below:

![image](https://user-images.githubusercontent.com/5555347/169845652-9a246de5-d6ad-450d-bce2-1038da9d8266.png)

This is probably ok since the agent still samples different actions, but it's nonetheless a problem. The correct implementation is to use `seed = seed + local_rank`.

### 2. stepping logic issue

- [x] #163 

After fixing #163, I was able to match the sample efficiency in the single GPU setting:

![image](https://user-images.githubusercontent.com/5555347/169860698-19270a81-95f1-4258-bfcb-e395af7d8c48.png)

However, the wall time is slower than I had expected. On a separate benchmark I made with CleanRL, the experiments show horovod should make Ant step 20% faster. 

Maybe it's the averaging stats overhead? In the CleanRL benchmark experiments I did not mess with stats at all.

![image](https://user-images.githubusercontent.com/5555347/169860812-38951961-24eb-423c-8ff9-6fe9f3de4f9c.png)

**Comment by Denys88** [comment]
@vwxyzjn  can we close it?

**Comment by vwxyzjn** [comment]
Closed by #171

**Comment by 1tac11** [comment]
Hi there
Is multi instance multi flu working?
