### ISSUE TITLE
Segmentation fault when importing env_configurations

### ISSUE THREAD

**Issue by fanshi14** [Denys88/rl_games#174]
Dear colleagues,

Thanks for your great contribution!

I found one problem when:
`$ import rl_games.common.env_configurations`
My PC will output: `Segmentation fault      (core dumped)`
I tried many different virtual environment but the same problem occurs.

Finally, I solved the problem by move `import rl_games.envs.test` into line 1 in [env_configurations.py](https://github.com/Denys88/rl_games/blob/master/rl_games/common/env_configurations.py#L3).

I do not know the exact reason why it could work after moving line 3 to the beginning.
Just let you know in case it is a potential bug.

PC environment: python 3.7, ubuntu 18.04, AMD 3990x cpu, NV RTX 3080.

**Comment by Denys88** [comment]
It is something new :)
did you use rl-games 1.1.4 or current master?

**Comment by Denys88** [comment]
Thanks @fanshi14  I think Ill just add your update but still not sure why it happens. if you can try it with python 3.9 it could help.
