### ISSUE TITLE
Latest version of rl_games not compatible with Isaac Gym

### ISSUE THREAD

**Issue by LeeChunHei** [Denys88/rl_games#175]
Hi, I was trying to update rl_games to the latest 1.4.0 version.
However, it shows that the latest version of rl_games failed to achieve the same performance in 1.1.4 which the Isaac Gym requires.

The environment I'm testing with is Humanoid, and the command I used is as follows:
python train.py task=Humanoid headless=True
and
python train.py task=Humanoid checkpoint=runs/Humanoid/nn/last_Humanoid_ep_500_rew_5396.84.pth test=True num_envs=9

When using 1.1.4, the humanoids can run forward, but with the latest version of rl_games, all the humanoids just collapse where they start.

May I know the changes between 1.1.4 and the latest version?
Or should I change something for the yaml config file to make it work in the latest version?

**Comment by Denys88** [comment]
Hi, as far as I know they didnt release next IsaacGymEnvs yet, 
Could you try my isaac gym envs fork please?
I moved observation normalization inside the model it might be a reason why it doesnt work for you.

**Comment by LeeChunHei** [comment]
> Hi, as far as I know they didnt release next IsaacGymEnvs yet, 
> 
> Could you try my isaac gym envs fork please?
> 
> I moved observation normalization inside the model it might be a reason why it doesnt work for you.

Hi, I think that is the the reason of it failing. 
I tried the fix you mentioned in https://github.com/Denys88/rl_games/issues/121#issuecomment-1048322560 and it works again.

**Comment by Denys88** [comment]
+ @ViktorM

**Comment by ViktorM** [comment]
Hello @LeeChunHei. The next version of IsaacGymEnvs will be fully compatible with the latest version of rl_games.

**Comment by LeeChunHei** [comment]
> Hello @LeeChunHei. The next version of IsaacGymEnvs will be fully compatible with the latest version of rl_games.

Hello @ViktorM, may I know if the next version of IsaacGymEnvs coming soon?
