### ISSUE TITLE
player.determenistic misspelling

### ISSUE THREAD

**Issue by etaoxing** [Denys88/rl_games#187]
"deterministic" is currently misspelled as "determenistic":
https://github.com/Denys88/rl_games/blob/1a890971d462c6dc7d632432377b0fc26509ae37/rl_games/common/player.py#L45

A few of the cfgs in IsaacGymEnvs ([ex.](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/6da538b44618afb9086be30371e5466ea182c2bf/isaacgymenvs/cfg/train/ShadowHandPPO.yaml#L77)) and OmniIsaacGymEnvs ([ex.](https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/blob/7e1c17adc57df3eacbe3e19ee72c554218265216/omniisaacgymenvs/cfg/train/ShadowHandPPO.yaml#L76)) use `deterministic: True`, but this shouldn't affect them since the default value is `True`.

Might be a good idea to accept both "deterministic" and "determenistic" for backwards compatibility.

**Comment by Denys88** [comment]
@etaoxing  thanks for the report.
Fixed it here: https://github.com/Denys88/rl_games/pull/188
I'll run a few tests and merge it.
