### ISSUE TITLE
Save and load state for Isaac Gym

### ISSUE THREAD

**Issue by supersglzc** [Denys88/rl_games#189]
Hi, I notice that we have functions get_env_state() and set_env_state() to save and load the info for the environment. Does it work in Isaac Gym?

**Comment by Denys88** [comment]
I think it is possible to add support for them in IG. cc @ViktorM

**Comment by ViktorM** [comment]
@supersglzc sorry for the delay with reply. Saving and loading state could be done in IG but you should do implement it manually for your env. You need to save state for all the objects and articulations in your env. Then also you need to save all the actions and re-apply them.
