### ISSUE TITLE
rl_device in Network

### ISSUE THREAD

**Issue by 1seck** [Denys88/rl_games#206]
Hi there, I am just wondering, in `A2CBuilder` in `Network`, which cuda device is actually used for the training and how would I hand down the `sim_device` respectively `rl_device` variables from `env_creator: create_env_thunk` in Isaacgmyenvs or alike into the Network class so I can put the tensors onto the right GPU for `torchrun` Multi-GPU training? Or is the right cuda-device set automatically?
Kind regards

**Comment by 1seck** [comment]
guess its done in A2Cagent.__init__()

**Comment by 1tac11** [comment]
Hi there
Did you manage to train on multiple instances not only standalone on multiple gpus?
