### ISSUE TITLE
Are visual agents supported?

### ISSUE THREAD

**Issue by davidoort** [Denys88/rl_games#214]
Hi,
as far as I can tell, the network architectures for the actor and critic in RL games are all MLPs, but I was wondering if there's a branch which contain encoders that are learnt by the agent and critic during training.

Thanks!

**Comment by ViktorM** [comment]
Hi @davidoort,

We have a number of examples available, that are not based only on MLPs. For example:
https://github.com/Denys88/rl_games/blob/master/rl_games/configs/atari/ppo_pong_envpool.yaml or https://github.com/Denys88/rl_games/blob/master/rl_games/configs/atari/ppo_breakout_envpool_resnet.yaml

**Comment by davidoort** [comment]
Super cool! Thanks a lot ❤️
