### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ZiyiLiubird** [Denys88/rl_games#221]
There is a TypError occurring when I run "python runner.py --train --file rl_games/configs/smac/3m_torch.yaml "

"File "/home/lzy/lzy/RL/official/rl_games/rl_games/common/vecenv.py", line 48, in seed
    self.env.seed(seed)
TypeError: 'NoneType' object is not callable"

**Comment by Denys88** [comment]
Starcraft2 env doesn't have seed setter function.
So I added empty seed. Please check current master.

**Comment by ZiyiLiubird** [comment]
> Starcraft2 env doesn't have seed setter function. So I added empty seed. Please check current master. [150ec47](https://github.com/Denys88/rl_games/commit/150ec478a68d949ec2375a1c5db79452148570e8)

thanks a lot
