### ISSUE TITLE
Question about the implementation of PPO actor loss function

### ISSUE THREAD

**Issue by ZiyiLiubird** [Denys88/rl_games#229]
https://github.com/Denys88/rl_games/blob/fa1c13cc10158ab42e829a0971a9dc9a4544b3b9/rl_games/common/common_losses.py#L24

In the PPO paper [](https://arxiv.org/pdf/1707.06347.pdf), the importance sampling ratio is (action_log_probs / old_action_log_probs_batch) instead of (old_action_log_probs_batch / action_log_probs). So I wonder why the implementation here is (old_action_log_probs_batch / action_log_probs). Thanks!

**Comment by Denys88** [comment]
mine is negative. it is the same :)

**Comment by ZiyiLiubird** [comment]
thanks a lot!
