### ISSUE TITLE
MAPPO with isaac gym 

### ISSUE THREAD

**Issue by Asad-Shahid** [Denys88/rl_games#234]
Hi,
Could you point to training with the MAPPO using rl_games? It seems there is already support for this as [here](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/issues/7#issuecomment-985945299). How do you perform the training in this specific case

Thanks

**Comment by Denys88** [comment]
hi! @Asad-Shahid  Ill answer tomorrow.

**Comment by ViktorM** [comment]
Hi @Asad-Shahid,

DexHand team has already added support for rl_games to their repo: https://github.com/PKU-MARL/DexterousHands#Use-rl_games-to-train-our-tasks

We also had a fork working with rl_games that is a bit behind the main repo: https://github.com/Denys88/DexterousHands

I'll test them tomorrow and will let you know if these repos are working with the latest version of rl_games.
