### ISSUE TITLE
Possibilities to use pointcloud as input for the SAC

### ISSUE THREAD

**Issue by robinvetsch** [Denys88/rl_games#249]
I use Isaac Gym including "rl_games" to train an RL-based path planning for a 6-DOF manipulator policy. The environment contains various obstacles that the robot must not touch. 

Is it possible with the current release of rl_games to use point cloud data as input to the SAC agent, or do the 3D point clouds have to be flattened and passed to the MLP?

Many thanks for the help.

**Comment by Denys88** [comment]
Hi @robinvetsch  here is an example in readme how to create custom neural network. https://github.com/Denys88/rl_games/blob/master/rl_games/envs/test_network.py
