### ISSUE TITLE
Getting error while testing 

### ISSUE THREAD

**Issue by qureshinomaan** [Denys88/rl_games#262]
I am able to train policies. 
But when loading the checkpoint to 'play' I am getting the following error : 
AttributeError: 'Envpool' object has no attribute 'render'

The command I am running is : 
python3 runner.py  --play -c runs/Walker2d-v4_envpool_30-07-00-39/nn/last_Walker2d-v4_envpool_ep_1000_rew__5242.4565_.pth --file ./rl_games/configs/mujoco/walker2d_envpool.yaml

I tried searching for a solution and it looks like a [problem](https://github.com/openai/gym/issues/762) with gym.

I am not sure if adding time is the best or recommended way?

**Comment by Denys88** [comment]
Thats a reason why I switch to the gym version of the mujoco to use render.
Could you set render to false in the config? Currently it is true/
player:
      render: True
AFAIK envpool doesn't support render at all.

**Comment by qureshinomaan** [comment]
Thanks a lot for the reply! Any workaround?

**Comment by Denys88** [comment]
If you want to render your policy you can reuse same checkpoint but with config with regular mojuco gym. And don't forget set render:True in yaml.

**Comment by fnuabhimanyu8713** [comment]
Hey @Denys88 do you have support for the opensource mujoco. Currently, the player calls gym.envs.mujoco.mujoco_env, which calls mujoco_py (old mujoco). How can I call the latest version of mujoco, which is not dependent on gym
