### ISSUE TITLE
Discrete and Continuous

### ISSUE THREAD

**Issue by mxllc** [Denys88/rl_games#282]
Hi, what could I do when I have both discrete and continuous variables for **A2CBase** in _a2c_common.py_?

**Comment by jiaweiz9** [comment]
I think the easiest way is just taking those discrete components as continuous ones. Or it will take too much of your time to write new classes.

**Comment by Denys88** [comment]
@mxllc @jiaweiz9  or oposite one.
I supported multi discrete space.
