### ISSUE TITLE
where is train.py?

### ISSUE THREAD

**Issue by Rowing0914** [Denys88/rl_games#293]
readme says train.py but where is it?

> Training
NVIDIA Isaac Gym

Download and follow the installation instructions of Isaac Gym: https://developer.nvidia.com/isaac-gym
And IsaacGymEnvs: https://github.com/NVIDIA-Omniverse/IsaacGymEnvs

Ant

python train.py task=Ant headless=True python train.py task=Ant test=True checkpoint=nn/Ant.pth num_envs=100

**Comment by Denys88** [comment]
https://github.com/isaac-sim/IsaacGymEnvs/blob/main/isaacgymenvs/train.py here is :)

**Comment by Rowing0914** [comment]
@Denys88 Thank you for your prompt response!
Did you benchmark PPO/SAC of this repo on those continuous tasks?

** I could only find the issue mentioning the previous benchmark on discrete tasks.
- https://github.com/Denys88/rl_games/issues/228

** SKRL seems to have compared rl-games to theirs on CartPole
- [Serrano-Muñoz, Antonio, et al. "skrl: Modular and flexible library for reinforcement learning." Journal of Machine Learning Research 24.254 (2023): 1-9.](https://arxiv.org/pdf/2202.03825)
