### ISSUE TITLE
[Q] Benchmark of PPO / SAC on continuous tasks like envs in IsaacGym

### ISSUE THREAD

**Issue by Rowing0914** [Denys88/rl_games#294]
@Denys88 Thank you for your prompt response to my previous issue!
Did you benchmark PPO/SAC of this repo on those continuous tasks?

** I could only find the issue mentioning the previous benchmark on discrete tasks.
- https://github.com/Denys88/rl_games/issues/228

** SKRL seems to have compared rl-games to theirs on CartPole
- [Serrano-Muñoz, Antonio, et al. "skrl: Modular and flexible library for reinforcement learning." Journal of Machine Learning Research 24.254 (2023): 1-9.](https://arxiv.org/pdf/2202.03825)

**Comment by Rowing0914** [comment]
Sorry, I just realised that benchmarking has been done in the repo of IsaacGymEnvs, e.g., [this training script](https://github.com/isaac-sim/IsaacGymEnvs/blob/main/isaacgymenvs/train.py)!

**Comment by Denys88** [comment]
Yes :)

**Comment by Rowing0914** [comment]
@Denys88 Thanks!
