### ISSUE TITLE
How to  load    the   policy  model  in  the real  robot ？

### ISSUE THREAD

**Issue by heartInsert** [Denys88/rl_games#300]
Hi ,  I  found  you   write  the   model  in  agent ,  I  have  trained  my  pth  file  ,    but  should  I   install  rl_games  in  my  real_robot ? And   how  to  load  the  model ?  Thanks very  much .

**Comment by dmakoviichuk-tt** [comment]
You can export it to the onnx. There are a some colab examples in readme.

**Comment by Denys88** [comment]
Please take a look at the onnx export examples. https://github.com/Denys88/rl_games?tab=readme-ov-file#quickstart-colab-in-the-cloud
Min idea is to use onnx runtime on robot.
