### ISSUE TITLE
[Bug] Need to pass old RNN states while running onnx inference

### ISSUE THREAD

**Issue by VineetTambe** [Denys88/rl_games#316]
Hey Authors,

Thanks for maintaining the repo! It's been great help! 
I was looking into the LSTM onnx export pipeline implementation in [rl_games/notebooks/train_and_export_onnx_example_lstm_continuous.ipynb](https://github.com/Denys88/rl_games/blob/master/notebooks/train_and_export_onnx_example_lstm_continuous.ipynb)

And noticed in the last cell where the inference in run after exporting the onnx the `out_state` and `hidden_state` are not updated from the predictions.

Shouldn't the while loop for inference look something like this:
```
while not is_done:
    outputs = ort_model.run(None, {"obs": np.expand_dims(obs, axis=0).astype(np.float32), "out_state.1" : out_state, "hidden_state.1" : hidden_state},)
    mu = outputs[0].squeeze(1)
    sigma = np.exp(outputs[1].squeeze(1))
    action = np.random.normal(mu, sigma)
    obs, reward, done, info = env.step(action)
    total_reward += reward
    num_steps += 1
    is_done = done

    # Update out_state and hidden_state to next states   
    out_state = outputs[3].squeeze(1)
    hidden_state = outputs[4].squeeze(1)

    screen = env.render(mode='rgb_array')
    plt.imshow(screen)
    display.display(plt.gcf())    
    display.clear_output(wait=True)
```

[ref](https://github.com/Denys88/rl_games/issues/146#issuecomment-1114083960)

**Comment by Denys88** [comment]
Ill take a look, thanks!

**Comment by Denys88** [comment]
@VineetTambe  could you clarify please:
I see 
```
    # Update out_state and hidden_state to next states   
    out_state = outputs[3].squeeze(1)
    hidden_state = outputs[4].squeeze(1)
```
and 
`    outputs = ort_model.run(None, {"obs": np.expand_dims(obs, axis=0).astype(np.float32), "out_state.1" : out_state, "hidden_state.1" : hidden_state},)`

**Comment by Denys88** [comment]
https://github.com/Denys88/rl_games/pull/317
