### ISSUE TITLE
Allegro Hand In-hand Manipulation Example Env Source Code

### ISSUE THREAD

**Issue by Lucky7Chess** [Denys88/rl_games#82]
On the bottom left of the example gif for Isaac Gym on the root readme on the master branch, there is a in-hand manipulation result on the Allegro Hand.  Where is the source for that env?  Was that created for use in rl_games?  I would like to recreate those results and add to that experiment if possible.  Thanks!

**Comment by ViktorM** [comment]
The source code will be released with the next Isaac Gym release around September. But reproducing these results is pretty straightforward - in the Shadow Hand environment, you just replace Shadow Hand with Allegro and only need to slightly modify observations and actions to take into account a smaller number of degrees of freedom of Allegro Hand.

**Comment by Lucky7Chess** [comment]
Cool yeah, I've done that swap already, just struggling to get it to actually train correctly so I was just hoping I could see that code to see what tweak I was missing.

**Comment by Lucky7Chess** [comment]
If there's any way we can get a prerelease beta version that could be helpful as well 😊
