### ISSUE TITLE
SAC Integration

### ISSUE THREAD

**Issue by cremebrule** [Denys88/rl_games#85]
Hi! Been using rl_games for a few months, awesome work guys :) Was wondering if the SAC integration will be ready anytime soon to try out?

Thanks!

**Comment by Denys88** [comment]
Hi, it is almost done but SAC disappointed me. Hard to get highest score, requires more tuning than we expected.
We will make one more pass  to test it and merge it :)

**Comment by Denys88** [comment]
Hi, @cremebrule  I just pushed first version of the SAC. It works fine with brax.
It has a few limitations which I am going to fix soon:
1) image inpit doesn't work. Only mlp
2) asymmetric critic is not yet implemented
3) nor rnn
Feel free to run it like this:
python runner.py --train --file rl_games/configs/brax/sac_humanoid.yaml
