### ISSUE TITLE
Multi-GPU usage

### ISSUE THREAD

**Issue by fil-mp** [Denys88/rl_games#95]
How can I use multiple GPUs for simulation and training? I am enabling horovod but it seems that it can only use one device.

**Comment by Denys88** [comment]
Could you show a whole error callstack?

**Comment by Denys88** [comment]
I've found what causes this issue: only rank 0 process checked  number of epochs. Ill make a fix in a few days.

**Comment by Denys88** [comment]
I've found 3 small issues:
1) exit on max epochs
2) exit on max rewards
3) uninitialized variable ( at least in discrete envs)
 I don't have access to the multigpu machine right now and simulated it with multi cpu. But it should work :)
https://pypi.org/project/rl-games/1.1.4/

**Comment by 1tac11** [comment]
Is this tested for multi instances or only multi GPUs on one instance? Since I had issues for multi instances.

**Comment by ViktorM** [comment]
It was tested on a single node, up to 8 GPUs with Isaac Gym. Each instance of Isaac Gym was running on its own GPU.
